### PR TITLE
Sketch symbols fuck yeah

### PR DESCRIPTION
**Pull request by JWhiteUX**
Beta Testing

### CODE REVIEW

**Comment by JWhiteUX** [comment]
Arg. I have no idea how to use the desktop app.

**Comment by fuggfuggfugg** [comment]
Lol, Are you trying to merge the branch into Master?

**Comment by JWhiteUX** [comment]
No, sorry about that. I wanted to clone the branch so I could move it into my plugins folder (and modify the default using Atom).

**Comment by fuggfuggfugg** [comment]
- To test, you can [click here to download ](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/archive/sketch-symbols-fuck-yeah.zip) the plugin. 
- Double click to install the plugin. 
- Locate the plugin in the folder and drag and drop it into Atom. 
- Make changes and save. In Sketch run "cmd+J" will automatically reflect the changes you made. 


May I ask what you want to modify? Asking because, I'm thinking to put another feature to put some defaults in manifest and read from there making it easy for user to customize some stuff like padding, bg color, text color

**Comment by JWhiteUX** [comment]
Thanks for that!

What I modify…
- Corner Radius (3px)
- Fill Color (green or blue)
- Default padding (10:30:10:30, or whatever I'm working on at the time)

Pain Points
- I use styles for buttons and there is no way to define an applied style
- I often change the text alignment based on the  position of the button (e.g if the button is on the right side of my mock, I switch to right alignment so the button grows to the left or inwards)
- Some of the time, I set the label/text alignment to `center aligned` so that the buttons remains centered (i.e a CTA)

**Comment by fuggfuggfugg** [comment]
Thanks, I can't guarantee you anything yet. But let me try and see if I can resolve some of your pain points. I only get time to work on this on the weekends unfortunately.

**Comment by JWhiteUX** [comment]
@fuggfuggfugg No rush. Just input/feedback.

**Pull request closed without merging**
